### ISSUE TITLE
New items are not craftable

### ISSUE THREAD

**Issue by BiggestLeaf** [Kamtheman56/Zelda_Mod#10]
Eye switches, shock switches, wooden pegs, and copper pegs crafting recipes do not work. In addition, the recipes for copper and wooden pegs are missing from the wiki. Timed eye switches and timed shock switches are able to be crafted no problem.

**Comment by Kamtheman56** [comment]
Thank you for the report! I immediately see what I did wrong and this will be fixed relatively soon.
