### ISSUE TITLE
Fierce Deity Sword is not classified as two handed in the Epic Fight Mod

### ISSUE THREAD

**Issue by CharmingOracle** [Kamtheman56/Zelda_Mod#11]
#### Description
The Fierce Deity Sword is not classified as two-handed in the Epic Fight Mod
#### Screenshots
![Biggoron Sword provided for comparison](https://github.com/Kamtheman56/Zelda_Mod/assets/93479373/ae443167-520e-42f1-b17b-febb1de4f6a7)

![Fierce Deity Sword](https://github.com/Kamtheman56/Zelda_Mod/assets/93479373/ea63fea1-1d50-4b48-b593-8d83277b008c)

#### To Reproduce
Look at the Fierce Deity Sword in one's inventory or use it with the Epic Fight Mod installed.

#### Tasks
Add the two-handed tag to the sword

**Comment by Kamtheman56** [comment]
Thank you for your dedicated bug reports! Cannot understate how useful they have been. Pushing a patch that will fix this and quite a few other issues. Will be available very soon!
