### ISSUE TITLE
Difference between Trailer and Gameplay

### ISSUE THREAD

**Issue by KurisuMiyamoto** [Kamtheman56/Zelda_Mod#15]
Goddess Hookshot still having a 2D sprite in-game, while in the 1.2 trailer it looks an awesome 3D model.

**Comment by Kamtheman56** [comment]
After testing a fresh download of version 1.2 I am unable to recreate this. Make sure you're on the latest version of Legendary Armory

**Comment by KurisuMiyamoto** [comment]
Yeah i'm using Zeldamod-1.2, Legendary Armory 1.0.0, the one that was upload like 22 hours ago

**Comment by KurisuMiyamoto** [comment]
![2024-09-23_15 07 42](https://github.com/user-attachments/assets/20bfb6c6-9356-418c-8e58-b84eaf8bd168)
![Captura de pantalla 2024-09-23 150824](https://github.com/user-attachments/assets/d59bb6e8-090c-497e-bc86-812a3d25d456)

**Comment by KurisuMiyamoto** [comment]
![Captura de pantalla 2024-09-23 151041](https://github.com/user-attachments/assets/3b0f4c64-8568-40b1-bee6-18ddd3118ba2)

**Comment by Kamtheman56** [comment]
Does the regular Clawshot also show up as a 2D item or is it a 3D model?

**Comment by KurisuMiyamoto** [comment]
Yeah, Twilight Princess Clawshot still 2D too

**Comment by Kamtheman56** [comment]
Hopefully this is fixed in the latest version 1.2.2
