### ISSUE TITLE
Compatibility suggestions.

### ISSUE THREAD

**Issue by KurisuMiyamoto** [Kamtheman56/Zelda_Mod#16]
I know it may be kinda hard, but it should be great if the Mirror Shield can reflect the Sunray of the Solar Projector from the mod Call of Yucatan.

A compatibiliy between ParaglidersMod's stamina system and the Stamina Fruit from Legendary Armoury sound good too!

**Comment by KurisuMiyamoto** [comment]
PD: i don't wanna open a new issue 'couse is just a little suggestion or question but, have you been thinking about add something like false doors, invisible blocks or any non-entity stuff to give more functionallity to the Lens of Truth?

**Comment by Kamtheman56** [comment]
The most likely is Stamina Fruit compatibility but it's pretty unlikely as Paragliders doesn't have an easy API to work with. In terms of adding "false blocks", there have been plans but it's a very low priority for me.
