### ISSUE TITLE
Can't get gibdo mask

### ISSUE THREAD

**Issue by SoftPaw6234** [Kamtheman56/Zelda_Mod#20]
Minecraft 1.20.1
Legendary armory 1.2.3
Other potentially relevant mods: Epic Fight 20.9.4
What should happen: click husk afflicted with weakness while holding gapple, get gibdo mask
What happened: husk has weakness, but won't take either normal or enchanded gapple

**Comment by Kamtheman56** [comment]
Thank you for reporting! This was an actually an error with not updating the Wiki page. 

The actual method for this is by applying Weakness to the Husk and then right clicking it with any Music Disc, Goat Horn, or Ocarina to obtain the mask. The wiki has been adjusted to include the proper method.
