### ISSUE TITLE
doubts about the configuration.

### ISSUE THREAD

**Issue by KurisuMiyamoto** [Kamtheman56/Zelda_Mod#24]
Is there any way to edit the size of the new bags? I think they're too op, with 256 arrows and 576 rupees, they feel like u don't have to upgrade them. I want to make them more accurate to the original bags. By the way, the wiki still doesn't have entries for the new items. 

PD: I think the new version is incompatible with the Supplementaries Mod, the Quiver bugs a lot (it seems like the number of arrows is permanently decreasing, but if you take off the arrows, they are still the same amount)

PD2: It looks like the Hover Boots have a bug when Sky Lands (deepcanionstudio) is installed, the boots just make a weird jump and doesn't work at all. i'm not saying that u have to fix these bugs but now u have been notified u of these bugs

**Comment by Kamtheman56** [comment]
Agreed about the bags, they have been nerfed as of version 1.3.1.

The Quiver should hopefully be fixed as of version 1.3.2, thank you for reporting the bugs! I am unable to recreate the Hover Boot glitch but they should be getting a rewrite within the next few updates so it hopefully will not be an issue.
