### ISSUE TITLE
Same thing

### ISSUE THREAD

**Issue by KurisuMiyamoto** [Kamtheman56/Zelda_Mod#25]
I was testing the reach of the hooksots and clawshots, i made a little area with marks every 5 blocks, the hookshot can reach the target and take the player there at the 15 blocks as max, it works like intended, same as the Longshot with 30 blocks, but the goddness clawshot have the same effectivity that the normal clawshot.

_note: this arena have 3 blocks of high so the ground doesn't stop the player when is gettin' taked, 'couse sometimes if u use any "grappling tool" (hookshot, longshot, clawshot and goddness clawshot) at the ground level, it can get cancelled randomly, leaving the player at middle of way._

is not too important but i'm trying to help, **we're very pleased with ur recent updates and we appreciate ur workso much.**

**Comment by KurisuMiyamoto** [comment]
https://github.com/user-attachments/assets/ac5926f7-8212-4cc6-87b7-b58ca43679de

**Comment by Kamtheman56** [comment]
This will be fixed in upcoming patch! Thank you for reporting the bug
