### ISSUE TITLE
Is it intended to be like this?

### ISSUE THREAD

**Issue by KurisuMiyamoto** [Kamtheman56/Zelda_Mod#26]
i was trying to make a puzzle with a chain of bomb flowers (like in Dragon Roost wall from WindWaker) but i notice that the Flower Bombs works weird.

![002e](https://github.com/user-attachments/assets/40c9288d-b34e-4a3f-9ab7-008093152434)

If u detonate a flower bomb, they will not break Secret Stones, but still breakin' normal blocks, even with "MobGriefing False", then if u have a flower bomb, u can throw it infinitely in all gamemodes.

https://github.com/user-attachments/assets/3edc3b2b-2c49-4d1a-b098-7e3627e47ec4

Suggestions:
 Flower Bomb Seed obtainable through putting a Flower Bomb in a crafting, like pumpkins or melons. with this, the player can just pick 
  and throw bombs without looting seeds when gather them.

![12321](https://github.com/user-attachments/assets/34052c99-f832-4200-b6be-2ef22d426780)

 More orientations to the block of Flower Bomb, so it can be grow in walls or roofs.

 The player needs to have a rason to preffer the normal bombs insted of flower bombs, they have to be wild or unestable, the "nerf" of 
  the explotion range can be easily bypass with some steps ahead more close of the objetive. So i suggest to make them trigger once the 
  player takes them in the hand, or something like the player cannot change his item in hand without throw the bomb before.

**Comment by Kamtheman56** [comment]
I agree with all of this! Wild Bomb Flowers now behave with this type of behavior, being able to be placed along any wall or ceiling. Wild and normal Bomb Flowers now also properly destroy any blocks marked in the "bomb_blocks" tag. 

Bombs in general are supposed to be a valuable resource so at least for this time you will not be able to easily obtain their seeds with the crafting recipe.

Bomb items now also properly deplete when using, thank you for submitting the bug report!
