### ISSUE TITLE
Spectator mode broken 

### ISSUE THREAD

**Issue by FreakyGamer** [Kamtheman56/Zelda_Mod#4]
As soon as i install the mod, my spectator mode behave really weird.
when in standing on the ground and switch to spectator i fall through the ground and cant fly or anything and when im in the water and switch into spectator its like im swimming but as soon as i touch land i once again fall through the world.

I use the version 1.0.6 for minecraft 1.20.1  with forge 47.2.0

**Comment by Kamtheman56** [comment]
What other mods do you have installed? I am unable to recreate this locally, so I'm guessing it's some sort of mod conflict

**Comment by FreakyGamer** [comment]
yeah im using this mod in an selfmade modpack 


[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Iron Chests: Restocked (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/ironchests)
[Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
[Crafting Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks)
[Thermal Foundation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
[ManyIdeas Core (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/manyideas-core)
[Metal Barrels (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/metal-barrels)
[Industrial Foregoing (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing)
[Paragliders (by Tictim)](https://www.curseforge.com/minecraft/mc-mods/paragliders)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Lucky's Cozy Home (by LuckyOwl)](https://www.curseforge.com/minecraft/mc-mods/cozy-home)
[MOA DECOR: LIGHTS (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-lights)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Mystical Agriculture (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture)
[Vampirism Integrations (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Elytra Slot (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot)
[Vampiric Ageing - A Vampirism Addon (by thedoctorofdoctoring)](https://www.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon)
[Cyclic (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/cyclic)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Macaw's Bridges - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-biome-o-plenty)
[OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Only Hammers [FORGE/FABRIC] (by Block_Legend001)](https://www.curseforge.com/minecraft/mc-mods/only-hammers-forge-fabric)
[ExpandAbility (by florensie)](https://www.curseforge.com/minecraft/mc-mods/expandability)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Refined Storage: Requestify (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/rs-requestify)
[Stabx Modern Guns (by stabilizer_king)](https://www.curseforge.com/minecraft/mc-mods/stabx-modern-guns)
[Refined Storage Addons (by raoulvdberge)](https://www.curseforge.com/minecraft/mc-mods/refined-storage-addons)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Pam's HarvestCraft 2 - Crops (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops)
[Thermal Locomotion (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-locomotion)
[Sinytra Connector (by Su5eD)](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[MOA DECOR: TOYS (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-toys)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Thermal Integration (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-integration)
[Simple Hats (by fonnymunkey)](https://www.curseforge.com/minecraft/mc-mods/simplehats)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Connected Glass (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/connected-glass)
[Thermal Expansion (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)
[Tesseract (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/tesseract)
[Lord's PC Mod (by lord_7302)](https://www.curseforge.com/minecraft/mc-mods/lords-pc-mod)
[Legendary Armory (by Kamtheman56)](https://www.curseforge.com/minecraft/mc-mods/legendary-armory-zelda-mod)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Pam's HarvestCraft 2 - Trees (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Doggy Talents Next (by dashiedev)](https://www.curseforge.com/minecraft/mc-mods/doggy-talents-next)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[MOA DECOR: BATH (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-bath)
[Ender's Delight (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/enders-delight)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[LibX (by noeppinoeppi)](https://www.curseforge.com/minecraft/mc-mods/libx)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Plain Grinder (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/plain-grinder)
[Titanium (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/titanium)
[Chisels & Bits - For Forge (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Botany Pots (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-pots)
[SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)
[Cluttered (by beelake)](https://www.curseforge.com/minecraft/mc-mods/cluttered)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[libIPN (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/libipn)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Time in a bottle [FORGE] (by MangoRage)](https://www.curseforge.com/minecraft/mc-mods/time-in-a-bottle-forge)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Applied Energistics 2 (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
[ShetiPhianCore (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore)
[FLIB (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/flib)
[Delightful (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/delightful)
[Zeta (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/zeta)
[Macaw's Roofs - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs-biomes-o-plenty)
[Refined Polymorphism (by ninety)](https://www.curseforge.com/minecraft/mc-mods/refined-polymorphism)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Ocean's Delight (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/oceans-delight)
[FramedBlocks (by XFactHD)](https://www.curseforge.com/minecraft/mc-mods/framedblocks)
[Thermal Cultivation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation)
[Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Inventory Profiles Next (by mirinimi)](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next)
[HammerLib (by Zeith)](https://www.curseforge.com/minecraft/mc-mods/hammer-lib)
[Diagonal Fences [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Factory Blocks (by Slaincow)](https://www.curseforge.com/minecraft/mc-mods/factory-blocks)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended)
[Twigs (by ninnih_)](https://www.curseforge.com/minecraft/mc-mods/twigs)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Vampirism - Become a vampire! (by maxanier)](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[MOA DECOR: COOKERY (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-cookery)
[GraveStone Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[FallingTree (Forge&Fabric) (by rakambda)](https://www.curseforge.com/minecraft/mc-mods/falling-tree)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Wonderful Hats (by Mizz)](https://www.curseforge.com/minecraft/mc-mods/wonderful-hats)
[Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Why stacks of 16? (by LaidBackSloth)](https://www.curseforge.com/minecraft/mc-mods/why-stacks-of-16)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Thermal Dynamics (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-dynamics)
[Craft slabs back into blocks [Fabric/Forge/NeoForge] (by Mars)](https://www.curseforge.com/minecraft/mc-mods/craft-slabs-back-into-blocks)
[Colorful Armor (by Torquebolt20)](https://www.curseforge.com/minecraft/mc-mods/colorful-armor)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[[1.20.1] OpenStairs (by HookerHeels)](https://www.curseforge.com/minecraft/mc-mods/openstairs)
[Iron Jetpacks (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks)
[FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
[Better Dogs X Doggy Talents Next (by mrblueyeti)](https://www.curseforge.com/minecraft/mc-mods/better-dogs-x-doggy-talents-next)
[Dark Paintings (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-paintings)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Torchmaster (by xalcon)](https://www.curseforge.com/minecraft/mc-mods/torchmaster)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[Thermal Innovation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/thermal-innovation)
[Continuity (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/continuity)
[Modonomicon (by kli_kli)](https://www.curseforge.com/minecraft/mc-mods/modonomicon)
[Healing Bed (by noxgame1230)](https://www.curseforge.com/minecraft/mc-mods/healing-bed)
[MOA DECOR: GARDEN (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-garden)
[ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Curious Armor Stands (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands)
[Macaw's Fences - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-biomes-o-plenty)
[Polymorphic Energistics (by ninety)](https://www.curseforge.com/minecraft/mc-mods/polymorphic-energistics)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[ExtraStorage (by 3divad99)](https://www.curseforge.com/minecraft/mc-mods/extrastorage)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Brizzle's Anime Paintings (by BrizzleWCBW)](https://www.curseforge.com/minecraft/mc-mods/brizzles-anime-paintings)
[Camera Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/camera-mod)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Dungeon Crawl (by xiroc_)](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[MOA DECOR: ART (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-art)
[Refined Storage (by raoulvdberge)](https://www.curseforge.com/minecraft/mc-mods/refined-storage)
[Dynamic Lights (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights)
[Mekanism-MoreSolarPanels (by Pocky)](https://www.curseforge.com/minecraft/mc-mods/mekanism-moresolarpanels)
[Extra Cooking Things (by gaelfe18asa)](https://www.curseforge.com/minecraft/mc-mods/extra-cooking-things)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Brizzle's Mystic Paintings (by BrizzleWCBW)](https://www.curseforge.com/minecraft/mc-mods/brizzles-mystic-paintings)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Beautify! (by Pandarix)](https://www.curseforge.com/minecraft/mc-mods/beautify-decorate)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Additional Lights (by mgen256)](https://www.curseforge.com/minecraft/mc-mods/additional-lights)
[MOA DECOR: HOLIDAYS (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-holidays)
[Night Lights (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/nightlights)
[Chisel Reborn (by Slaincow)](https://www.curseforge.com/minecraft/mc-mods/chisel-reborn)
[ManyIdeas Doors (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/manyideas-doors)
[End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Macaw's Furnitures - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures-biomes-o-plenty)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/lendercataclysm)
[Recipes Library (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/recipes-library)
[Werewolves - Become a Beast! (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast)
[Monster Plus (by Nitespring)](https://www.curseforge.com/minecraft/mc-mods/monster-plus)
[Athena (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/athena)
[Mystical Agradditions (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions)
[Variant Tools and Weaponry - More Weapons (by attila1990)](https://www.curseforge.com/minecraft/mc-mods/variant-tools-and-weaponry-more-weapons)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[MrCrayfish's Gun Mod [Unofficial] (by MikhailTapio)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod-unofficial)
[Pocket Storage (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/pocket-storage)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Mekanism Additions (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions)
[CosmeticArmours (by iiJowonny)](https://www.curseforge.com/minecraft/mc-mods/cosmeticarmours)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Forgified Fabric API (by Su5eD)](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api)
[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[EdivadLib (by 3divad99)](https://www.curseforge.com/minecraft/mc-mods/edivadlib)
[Mystical Customization (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-customization)
[Smarter Farmers (farmers replant) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant)
[Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Handcrafted (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Immersive Engineering (by BluSunrize)](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
[FTB Ultimine (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
[Fantasy's Furniture (by ApexModder)](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture)
[Magic Vibe Decorations (Crystals, Halloween additions) (by LillouArts)](https://www.curseforge.com/minecraft/mc-mods/magic-vibe-decorations)
[MultiBeds (by ShetiPhian)](https://www.curseforge.com/minecraft/mc-mods/multibeds)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Cyclops Core (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/cyclops-core)
[Travel Anchors (by CastCrafter)](https://www.curseforge.com/minecraft/mc-mods/travel-anchors)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[The One Probe (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)
[MC style paintings (by SP_Studios)](https://www.curseforge.com/minecraft/mc-mods/minecraft-style-paintings)
[MOA DECOR: SCIENCE (by moa666creator)](https://www.curseforge.com/minecraft/mc-mods/moa-decor-science)
[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Angel Ring (by DenisMasterHerobrine)](https://www.curseforge.com/minecraft/mc-mods/angel-ring)
[RightClickHarvest (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/rightclickharvest)
[Applied Mekanistics (by ramidzkh)](https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics)
[Ears (+ Snouts/Muzzles, Tails, Horns, Wings, and More) (by unascribed)](https://www.curseforge.com/minecraft/mc-mods/ears)
[Flux Networks (by sonar_sonic)](https://www.curseforge.com/minecraft/mc-mods/flux-networks)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Workshop for handsome adventurer (by MoonFather)](https://www.curseforge.com/minecraft/mc-mods/workshop-for-handsome-adventurer)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Zelda, Legend of the Master Sword (by Mezimaru)](https://www.curseforge.com/minecraft/mc-mods/zelda-legend-of-the-master-sword)
