### ISSUE TITLE
flight bug (majoras mask)

### ISSUE THREAD

**Issue by KeykKal** [Kamtheman56/Zelda_Mod#6]
Hello. i can't seem to fly using majorask mask and other mods that would give me creative flight in survival also dont except i have majoras mask equipped at the same time.
i deactiveted all other mods and it still wont work.
one mod i use is apotheosis and its way to enable survival flight also wont work when paired together with this mod.
i know it is probably already worked on but the latest update doesn't seem to have fixed it so i just wanted to make this report to be save.

**Comment by Kamtheman56** [comment]
Thanks for reporting this! I thought I had it fixed, but apparently not. Will be looking to push a patch with it asap.

**Comment by Kamtheman56** [comment]
I have pushed a patch that should have fixed this issue! I have tested it with several mods that add flight and they all seem to work, so hopefully this is dealt with.
