### ISSUE TITLE
Hero's Bow Can't Be Enchanted in Anvil

### ISSUE THREAD

**Issue by entslaia** [Kamtheman56/Zelda_Mod#8]
The Hero's Bow can be enchanted in an enchanting table, but using an enchanted book on it in an anvil will not work. Have tried different books (eg Punch, Power, Mending) both before and after it has been enchanted in a table.

**Comment by Kamtheman56** [comment]
This was an oversight and has been fixed! Pushing a patch with this and some other fixes, will be available soon!
