### ISSUE TITLE
Incompatibility with Artifacts mod

### ISSUE THREAD

**Issue by CharmingOracle** [Kamtheman56/Zelda_Mod#9]
#### Description
When attempting to launch the game with both Legendary Armory and Artifacts installed, the game crashes before the Forge loading screen can show up.

#### To Reproduce
Launch both Legendary Armory and Artifacts with both of their necessary dependencies. 

#### Files
Crash log:
[MC Logs Report](https://mclo.gs/f69Z7le)
[Crash_report.txt](https://github.com/Kamtheman56/Zelda_Mod/files/15087451/Crash_report.txt) #

**Comment by Kamtheman56** [comment]
Thank you for submitting a crash report! ExpandAbility is baked into Legendary Armory but only for the Modrinth release, so should be an easy fix. In the meantime please download the file from Curseforge as it is not a baked in dependent with that download. This will be fixed within the upcoming patch

**Comment by CharmingOracle** [comment]
I can confirm that this fix worked. Thank you.
